-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 15:18:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_travel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_travel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_travel` DEFAULT CHARACTER SET utf8mb4 ;
USE `my_travel` ;

-- -----------------------------------------------------
-- Table `my_travel`.`trip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_travel`.`trip` (
  `trip_id` BIGINT NOT NULL AUTO_INCREMENT,
  `trip_name` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`trip_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_travel`.`itinerary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_travel`.`itinerary` (
  `iditinerary_id` BIGINT NOT NULL AUTO_INCREMENT,
  `trip_id` BIGINT NOT NULL,
  `departure_place` VARCHAR(45) NOT NULL,
  `destination` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`iditinerary_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
